apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1 #more than 1 it needs to be a statefulSets to manage multiple connections tho the db
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-pwd

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo # Car le service est appelé en 1er avant de rediriger vers les pods correspondants, pas les deployment, le deployment est juste un conteneur ce qui interesse c est le pod
  ports:
    - protocol: TCP
      port: 27017 # can choose any number but to keep thing simple use the same value
      targetPort: 27017 # should match the pod port

